### ISSUE TITLE
Change default output?

### ISSUE THREAD

**Issue by onyonderlea** [guyleonard/get_jgi_genomes#5]
Hi! I'm not much of a scripter so I was wondering: why exactly is amino acid sequence a default output? From my understanding, JGI stores genomes - so is there a step in the code that translates the nucleotide sequence? Is there a way to get nucleotide sequences as output? Thanks!

**Comment by guyleonard** [comment]
Hey!

Sorry, I totally missed this. Yes, I have made an update to include other output now; proteins remain the default output (they are the predicted genes from the portal, no translation happens with this program) and then you can modify the command with the otpions "-A get assembly", "-C get CDS", "-g get GFF" and "-t get transcripts". Hope that helps.
