### ISSUE TITLE
Download mycocosm protein files - pep directory empty

### ISSUE THREAD

**Issue by sgleich** [guyleonard/get_jgi_genomes#7]
Hi! I was hoping to download all of the protein files from the JGI mycocosm database. I tried to do this using the example command you provided in the README file (./bin/get_jgi_genomes -c signon.cookie -f -l) but the resulting /fungi/pep directory is empty. The resulting /fungi/pep_list.txt has all of the file IDs and URLs (e.g., Aaosphaeria arxii CBS 175.79 v1.0 Aaoar1 https://genome.jgi.doe.gov/portal/Aaoar1/download/Aaoar1_GeneCatalog_proteins_20140429.aa.fasta.gz).

Do you have any idea why the pep files didn't download? I didn't notice any errors when running the 'get_jgi_genomes' script, so any insight is greatly appreciated!

**Comment by guyleonard** [comment]
Hi, 

Just double checking that you logged in first and that the signon.cookie was generated correctly.

Can you check - don't show me - that there is more than just:

`\# Netscape HTTP Cookie File

\# https://curl.se/docs/http-cookies.html

\# This file was generated by libcurl! Edit at your own risk.
`
in your "signon.cookie" fille.

I have noticed that JGI's SSL certificate is out of date - at least I get this message "curl: (60) SSL certificate problem: certificate has expired"

The only way have found to resolve it is to use "--insecure" with the "curl" command. I am not 100% sure I want to update the repo currently to do that, but in the meantime you could add that to the script and see if it fixes things (you might need to delete your current signon.cookie and fungi_files.xml first)

E.g. Try this and login and try downloading again
` sed -i 's/curl /curl --insecure /' ./bin/get_jgi_genomes
`

**Comment by guyleonard** [comment]
Oh, I realise I have been a bit dense and overly complicated in my response, I think maybe you wanted to download the aa,fasta for each species and you had actually signed in okay. Ooops.

To download files by asking for each species separately: e.g.

`./bin/get_jgi_genomes -c signon.cookie -f -i Aaoar1
`

The "-f -l" options just create a list from the XML.

You could do this though: 

`awk '{print $2}' fungi/pep_list.txt | while read -r jgi_id; do ./bin/get_jgi_genomes -c signon.cookie -f -i "$jgi_id"; done
`

Which will go through the list, line by line and run the command to pull the protein files for each! :) 

OR

Omit the "-l" from your original command and it should download everything - sorry it is late and has been a long day.

**Comment by sgleich** [comment]
Great! Issue resolved. Thank you so much!
