### ISSUE TITLE
Issues with missing Perl modules

### ISSUE THREAD

**Issue by crt-pantner** [guyleonard/get_jgi_genomes#9]
# The issue:

After cloning the repository and running the "get_jgi_genomes" file using the command "perl get_jgi_genomes" from the "bin" folder of the repo, the program exits with the following output: 

`get_jgi_genomes/bin$ perl get_jgi_genomes`

```
Can't locate XML/LibXML.pm in @INC (you may need to install the XML::LibXML module) (@INC entries checked: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.38.2 /usr/local/share/perl/5.38.2 /usr/lib/x86_64-linux-gnu/perl5/5.38 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.38 /usr/share/perl/5.38 /usr/local/lib/site_perl) at get_jgi_genomes line 12.
BEGIN failed--compilation aborted at get_jgi_genomes line 12.
```

# What am i using:

Windows subsystem for linux, Ubuntu-24.04 Version 2 running on Windows 11 Pro

# What i have tried:
`sudo cpanm XML::LibXML` to install the missing dependecies, with little success, as installation fails since (as far as I understand) other dependencies for it are missing, among them being: "Net::SSLeay", "IO::Socket::SSL", "Alien::Libxml2", the command used to install the dependencies appears to try to install the dependecies for XML::LibXML, yet fails to do so for whatever reason - however this could just be a problem with my system. 

```
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0210.tar.gz ... OK
==> Found dependencies: Alien::Libxml2
--> Working on Alien::Libxml2
Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/Alien-Libxml2-0.19.tar.gz ... OK
Configuring Alien-Libxml2-0.19 ... OK
==> Found dependencies: IO::Socket::SSL, Net::SSLeay
--> Working on IO::Socket::SSL
Fetching http://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.089.tar.gz ... OK
==> Found dependencies: Net::SSLeay
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.94.tar.gz ... OK
Configuring Net-SSLeay-1.94 ... N/A
! Configure failed for Net-SSLeay-1.94. See /root/.cpanm/work/1725118846.13053/build.log for details.
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.089.
! Installing the dependencies failed: Module 'IO::Socket::SSL' is not installed, Module 'Net::SSLeay' is not installed
! Bailing out the installation for Alien-Libxml2-0.19.
! Installing the dependencies failed: Module 'Alien::Libxml2' is not installed
! Bailing out the installation for XML-LibXML-2.0210.
```

# Additional notes:
When trying to run the program for the first time, a simmilar output appeared as described in "The issue:", however indicating a missing List::MoreUtils module. After successfull installation with cpanminus it was replaced with the issue of the missing XML::LibXML module. 

Hopefully the issues have been described clearly enough.

**Comment by crt-pantner** [comment]
After trying to install the missing modules with cpanminus I decided to try and install the two modules with conda into a seperate environment, I managed to get the script to run. 

The packages I installed are:
 - https://anaconda.org/bioconda/perl-xml-libxml
 - https://anaconda.org/bioconda/perl-list-moreutils

**Comment by guyleonard** [comment]
Hey!

I am glad you managed to get things running with conda in the end! :) 

I will add to the readme to make people more aware perl modules are needed :)
